version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fuzzy-backend
    ports:
      - "8080:8080"
    networks:
      - fuzzy-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fuzzy-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - fuzzy-net

networks:
  fuzzy-net:
    driver: bridge
